"""
Simon Says Memory Game
A terminal-based working memory experiment that generates color
sequences for the player to repeat. The color pool expands every
few levels, making the game progressively harder. Performance data
is saved to data/results.csv after each game session.
"""

import csv
import os
import random
import time

# All possible colors, unlocked progressively as levels increase.
# Starting with 4 colors; more are added at level thresholds below.
ALL_COLORS = ["red", "blue", "green", "yellow", "purple", "orange", "white"]
 
# Level thresholds at which a new color is unlocked.
# Dictionary maps level number -> color that gets added (Ch. 4.1)
COLOR_UNLOCK_LEVELS = {
    5: "purple",
    8: "orange",
    11: "white",
}

def get_active_colors(level: int) -> list:
    """
    Return the list of colors available at the given level.
 
    Starts with the first 4 colors. Each time the player reaches a
    threshold level defined in COLOR_UNLOCK_LEVELS, one new color is
    added to the pool, making correct guesses harder.
 
    Parameters
    ----------
    level : int
        The current game level.
 
    Returns
    -------
    list
        The colors available for sequence generation at this level.
    """
    # Start with the base 4 colors
    active = ALL_COLORS[:4].copy()
 
    # Loop through unlock thresholds; add color if level reached
    # Dictionary iteration covered in Ch. 4.1
    for unlock_level, color in COLOR_UNLOCK_LEVELS.items():
        if level >= unlock_level:
            active.append(color)
 
    return active
 
 
def generate_sequence(level: int, active_colors: list) -> list:
    """
    Generate a random color sequence for the current level.
 
    Parameters
    ----------
    level : int
        The current game level; determines the length of the sequence.
    active_colors : list
        The pool of colors to draw from at this level.
 
    Returns
    -------
    list
        A list of color name strings of length `level`.
    """
    # List comprehension to build the sequence (Ch. 2.0)
    return [random.choice(active_colors) for _ in range(level)]
 
 
def play_sequence(sequence: list) -> None:
    """
    Display the color sequence to the player one color at a time.
 
    Each color is printed with a short pause so the player can
    memorize the order before being asked to repeat it.
 
    Parameters
    ----------
    sequence : list
        The list of color name strings to display.
    """
    print("\nWatch the sequence:")
 
    # Loop over each color and print it with a delay (Ch. 2.0)
    for color in sequence:
        print(f"  --> {color}")
        time.sleep(0.8)
 
    # Clear the screen with blank lines so the sequence is hidden
    print("\n" * 20)
 
 
def get_user_input(length: int) -> list:
    """
    Prompt the player to type their color sequence guess.
 
    Parameters
    ----------
    length : int
        The expected number of colors (shown in the prompt).
 
    Returns
    -------
    list
        The player's input split into a list of lowercase color strings.
    """
    prompt = f"Enter {length} color(s) separated by spaces: "
    user_response = input(prompt)
 
    # .lower() and .split() are string methods from Ch. 1.3
    return user_response.lower().split()
 
 
def check_player_input(sequence: list, user_input: list) -> bool:
    """
    Check whether the player's input matches the correct sequence.
 
    Parameters
    ----------
    sequence : list
        The correct color sequence generated by the game.
    user_input : list
        The sequence entered by the player.
 
    Returns
    -------
    bool
        True if the sequences match exactly, False otherwise.
    """
    # Comparison operator == on lists (Ch. 1.6, Ch. 2.4)
    return sequence == user_input
 
 
def display_results_summary(results: list) -> None:
    """
    Print a summary of the player's performance after the game ends.
 
    Calculates highest level reached, number of correct rounds, and
    average reaction time using list comprehensions and built-in
    functions
    
    Parameters
    ----------
    results : list
        A list of [round, correct, reaction_time] rows collected
        during the game session.
    """
    # Guard clause: nothing to summarize if no rounds were played
    if not results:
        print("No rounds played.")
        return
 
    highest_level = len(results)
 
    # List comprehensions to filter correct rounds and extract times
    correct_rounds = [row for row in results if row[1] == 1]
    num_correct = len(correct_rounds)
 
    reaction_times = [row[2] for row in results]
    avg_reaction_time = sum(reaction_times) / len(reaction_times)
 
    print("\n--- Game Over! Here are your results ---")
    print(f"  Highest level reached : {highest_level}")
    print(f"  Correct rounds        : {num_correct} / {highest_level}")
    print(f"  Average reaction time : {avg_reaction_time:.2f} seconds")
 
 
def save_data(results: list) -> None:
    """
    Save the session's round-by-round results to data/results.csv.
 
    Creates the data/ directory automatically if it does not exist,
    using os.makedirs() from the os module (Ch. 5.0).
 
    Parameters
    ----------
    results : list
        A list of [round, correct, reaction_time] rows to write.
    """

    os.makedirs("data", exist_ok=True)
 
    # File I/O with 'with' statement for automatic closing (Ch. 2.9)
    with open("data/results.csv", "w", newline="") as file_handle:
        writer = csv.writer(file_handle)
        writer.writerow(["round", "correct", "reaction_time"])
        writer.writerows(results)
 
 
def run_game() -> None:
    """
    Run the main Simon Says game loop.
 
    Each round the sequence grows by one color. New colors are
    unlocked at level thresholds, expanding the pool the player
    must remember from.
    """
    level = 1
    results = []
    keep_playing = True  
 
    print("=== Welcome to Simon Says! ===")
    print("Starting colors: red, blue, green, yellow")
    print("New colors unlock at levels 5, 8, and 11!")
    print("Memorize the sequence, then type it back.\n")
 
    while keep_playing:
        # Get the color pool available at this level
        active_colors = get_active_colors(level)
 
        # Announce a newly unlocked color at threshold levels (Ch. 1.7)
        if level in COLOR_UNLOCK_LEVELS:
            new_color = COLOR_UNLOCK_LEVELS[level]
            print(f"*** Level {level}: '{new_color}' has been added! ***")
            print(f"Active colors: {', '.join(active_colors)}\n")
 
        print(f"--- Level {level} "
              f"({len(active_colors)} colors in play) ---")
 
        # Generate and show the sequence for this level
        sequence = generate_sequence(level, active_colors)
        play_sequence(sequence)
 
        # Time the player's response (time module, Ch. 5.0)
        start_time = time.time()
        user_input = get_user_input(level)
        reaction_time = round(time.time() - start_time, 2)
 
        correct = check_player_input(sequence, user_input)
 
        # Conditional branching on correctness (Ch. 1.7)
        if correct:
            print("Correct! Moving to the next level.\n")
            results.append([level, 1, reaction_time])
            level += 1
        else:
            print(f"Wrong! The sequence was: {' '.join(sequence)}")
            results.append([level, 0, reaction_time])
            keep_playing = False  
 
    # Show summary and save after the game ends
    display_results_summary(results)
    save_data(results)
    print("\nData saved to data/results.csv")
 
 
def main() -> None:
    """Entry point: wrap run_game() so the module can also be imported."""
    run_game()


if __name__ == "__main__":
    main()
